# Generated by Django 3.2.6 on 2021-11-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/blog/'),
        ),
    ]
