# Generated by Django 3.2.6 on 2021-09-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210913_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default='blog_default.png', null=True, upload_to='images/blog/'),
        ),
    ]
