# Generated by Django 3.2.6 on 2021-09-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_post_blog_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='post',
            name='post_view',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
