# Generated by Django 3.2.6 on 2021-09-14 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210914_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_view',
            new_name='post_views',
        ),
    ]
