# Generated by Django 3.2.6 on 2021-09-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/bio/')),
                ('facebook', models.URLField(blank=True, default='#', max_length=300, null=True)),
                ('instagram', models.URLField()),
                ('twitter', models.URLField(blank=True, default='#', max_length=300, null=True)),
                ('youtube', models.URLField(blank=True, default='#', max_length=300, null=True)),
                ('snapchat', models.URLField(blank=True, default='#', max_length=300, null=True)),
            ],
        ),
    ]
