# Generated by Django 3.2.6 on 2021-09-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='image',
            field=models.ImageField(null=True, upload_to='images/bio/'),
        ),
    ]
